Import('COMPILER')

SConscript(dirs = ['common', 'engine', 'util', 'particle_engine'])

if COMPILER.is_mac():
	SConscript(dirs = ['video_mac'])
elif COMPILER.is_unix():
	SConscript(dirs = ['video_unix','config'])
else:
	SConscript(dirs = ['video_win32','config'])
