import os

Import('base_env BUILD_DIR')

files = [
    'readme.txt',
    'game.sgm',
    'images/sphereicon.png',
    'images/bg_320_240.png',
    'images/bgi_320_240.png',
    'images/bg_640_480.png',
    'images/bgi_640_480.png',
    'scripts/main.js',
    'scripts/bounceoutimage.js',
    'scripts/fadeout.js',
    'scripts/gamelist.js',
    'scripts/globalcursor.js',
    'scripts/moveimage.js',
    'scripts/movetext.js',
    'scripts/phaseintext.js',
    'scripts/textwrap.js',
    'scripts/tickerbar.js' ]

for f in files:
    base_env.Install(
        os.path.join(os.path.join(BUILD_DIR, 'startup'),
                     os.path.split(f)[0]), f)
