import sys
import autocons

Import('base_env BUILD_DIR COMPILER')

env = base_env.Clone()

if (COMPILER.is_unix()):
	base_env.Prepend(LIBS = ['z'])
COMPILER.SetupSphereCommon(env)
COMPILER.SetupAudiere(env)
COMPILER.SetupCorona(env)
COMPILER.SetupJS(env)
COMPILER.SetupMNG(env)
COMPILER.SetupParticleEngine(env)

if (COMPILER.needs_sdl()):
    COMPILER.SetupSDL(env)

engine_sources = Split("""
    SpritesetServer.cpp
    benchmark.cpp
    engine.cpp
    log.cpp
    map_engine.cpp
    render.cpp
    rendersort.cpp
    parameters.cpp
    script.cpp
    sfont.cpp
    sfxr.cpp
    simage.cpp
    smap.cpp
    sphere.cpp
    ssfxr.cpp
    sspriteset.cpp
    swindowstyle.cpp
    PlayerConfig.cpp
    """)

if (COMPILER.is_unix()):
    COMPILER.UnixSubsystem(env)
    md = 'unix'

print "Using subsystem: " + md

if (COMPILER.is_unix()):
	env.Append(LIBS = ['dl', 'js'])

engine = env.Program('engine', engine_sources)
env.Install(BUILD_DIR, engine)

SConscript(dirs = [md])
