Import("base_env BUILD_DIR COMPILER")

env = base_env.Clone()
COMPILER.SetupWXWidgets(env)


config = env.Program('config', Split("""
    ConfigApp.cpp
    ConfigFrame.cpp
    DialogSphere8.cpp
    DialogSphere32.cpp
    DialogSphereGL.cpp
"""))

env.Install(BUILD_DIR, config)
