import os
import types

Import('base_env BUILD_DIR COMPILER')

env = base_env.Clone()

def VideoDriver(name, source, libs):
    global env
    drv = env.Clone()
    drv.Append(LIBS = libs)
    driver = drv.SharedLibrary(name, source)
    drv.InstallAs(os.path.join(BUILD_DIR, 'system/video/' + name + '.so'), driver)


Export('VideoDriver')

SConscript(dirs = ['sdl32', 'sdl_gl'])
